from src.python.bbn_medic.common import Prompt


class PromptClusterer:

    def cluster(self, prompts: list[Prompt]):
        """
        Cluster a list of prompts.

        :param prompts: list of Prompt objects to be clustered
        :return: the list of clusters generated by the clustering method
        :rtype: list[PromptCluster]
        """
        # TODO
        return